nm = read.csv("narendramodi_tweets.csv")
View(nm)
str(nm)
colSums(is.na(nm))
tweet = gsub("[^A-Za-z///']" , " ", nm$text)
head(tweet,5)
doc = Corpus(VectorSource(tweet))
doc = tm_map(doc,removeNumbers)
doc = tm_map(doc,content_transformer(tolower))
doc = tm_map(doc,removePunctuation)
doc = tm_map(doc,removeWords,stopwords(kind = "english"))
custom_stop = c("https" , "amp" , "pmoindia" , "will")
doc = tm_map(doc,removeWords,custom_stop)
doc = tm_map(doc,stripWhitespace)
dtm = DocumentTermMatrix(doc)
dtm
dtm_without_sparsity = removeSparseTerms(dtm,0.97)
dtm_without_sparsity
dtm1 = as.matrix(dtm)
df = sort(colSums(dtm1),decreasing = TRUE)
df = data.frame(word = names(df),freq = df)
dtmr = DocumentTermMatrix(doc, control = list(wordLengths = c(4,Inf)))
dtmr
dtm2 = as.matrix(dtmr)
df2 = sort(colSums(dtm2),decreasing = TRUE)
df2 = data.frame(word = names(df2),freq = df2)
findFreqTerms(dtmr , lowfreq = 100)
findAssocs(dtmr,'development',0.20)
wordcloud2(df2 , size = 1.6, color = 'random-dark' , backgroundColor = "gray")
